apiVersion: apps/v1
kind: Deployment
metadata:
  name: trend-app
  labels:
    app: trend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trend
  template:
    metadata:
      labels:
        app: trend
    spec:
      containers:
      - name: trend-container
        image: arun0801/trend-app:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: nginx-conf-vol
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        volumes:
      - name: nginx-conf-vol
        configMap:
          name: nginx-config
